site_name: Matura Zusammenfassung
# site_url: https://matura-zusammenfassung.readthedocs.io/de/latest/
nav:
    - Home: index.md
    - Mathematik:
      - Stoffplan: mathe/mathematik.md
      - Vektorgeometrie:
        - Vektorgeometrie I: mathe/vektorgm/vgm1.md
        - Skalar-, Vektor- und Spatprodukt: mathe/vektorgm/s-v-spProd.md
        - Die Gerade im Raum: mathe/vektorgm/gImRaum.md
        - Die Ebene im Raum: mathe/vektorgm/eImRaum.md
      - Stochastik:
        - Kombinatorik: mathe/stochastik/komb.md
        - Wahrscheinlichkeitsrechnung: mathe/stochastik/wrechnung.md
        - Wahrscheinlichkeitsverteilung: mathe/stochastik/wvert.md
      - Analysis:
        - Exponentielles Wachstum und Logarithmus: mathe/analysis/expWachstum&Log.md
        - Endliche Folgen und Reihen: mathe/analysis/endlF&R.md
        - Grenzwerte und unendliche Prozesse: mathe/analysis/grenzw&unendlP.md
        - Repetition Funktionen und Ergänzungen: mathe/analysis/repF&E.md
        - Differentialrechnung I: mathe/analysis/diff1.md
        - HP, TP, WP und Extremalprobleme: mathe/analysis/extremalp.md
        - Integralrechnung I: mathe/analysis/int1.md
        - Differentialrechnung II: mathe/analysis/diff2.md
        - Integrations-Methoden: mathe/analysis/intMeth.md
        - Gewöhnliche Differentialgleichungen: mathe/analysis/gewDiff.md
    - Physik:
      - Stoffplan: physik/physik.md
      - Mechanik: physik/mechanik.md
      - Kreisbewegung: physik/kreisb.md
      - Hydrostatik/Aeorostatik: physik/hydro-aeors.md
      - Wärme: physik/wärme.md
      - Elektrizität: physik/elek.md
      - Magnetismus: physik/mag.md
      - Kernphysik: physik/kernp.md
      - Schwingungen und Wellen, Akustik: physik/s-w-akustik.md
      - Spezielle Relativitätstheorie: physik/spRel.md
      - Allgemeine Relativitätstheorie: physik/allRel.md
      - Quantenphysik: physik/quantenp.md
      - Physik mit Differential- und Integralrechnung: physik/diffint.md
    - AM:
      - Stoffplan: am/am.md
      - Beurteilende Statistik: am/beurtS.md
      - Lineare Abbildungen: am/linAb.md
      - Affinitäten: am/aff.md
      - Erstes Rechnen mit Matrizen: am/erstMat.md
      - Nichtgeometrische Anwendungen von Matrizen: am/ngmMat.md
      - Parameterfunktionen: am/paramF.md
    - Geographie:
      - Stoffplan: gg/geographie.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: sick-dark
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    # Light mode
    - deep orange: "(prefers-color-scheme: light)"
      scheme: sick-light
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides

  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - header.autohide
plugins:
  - search
  - git-revision-date-localized
  - pandoc:
      combined: true
      pandoc_extra_args: --resource-path=.:docs:img
  - print-site:
      path_to_pdf: '..\..\pandoc\combined.pdf'
      add_to_navigation: false
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 6
  - def_list
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
repo_url: https://github.com/anrodom/matura-zusammenfassung
repo_name: GitHub | anrodom
edit_uri: "blob/main/docs/"
# extra:
#  disqus: maturazusammenfassung
