name: matura-zusammenfassung
channels:
  - conda-forge
  - defaults
dependencies:
  - pandoc==2.9.2
  - python==3.9.2
  - pip==21.1
  - pip:
    - pymdown-extensions==8.1.1
    - mkdocs-material==7.1.1
    - mkdocs-git-revision-date-localized-plugin==0.9
    - mkdocs-macros-plugin==0.5.5
